apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-postgres-pv-volume
  namespace: hyuabot-dev
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/dev/postgres-pv-volume
  storageClassName : dev-postgres-pv-storage
