apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-postgresql-pv-claim
  namespace: hyuabot-dev
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: dev-postgres-pv-storage
