apiVersion: v1
kind: Service
metadata:
  name: hyuabot-api
  namespace: hyuabot-dev
  labels:
    app: hyuabot-api
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30000
  selector:
    app: hyuabot-api