apiVersion: batch/v1
kind: CronJob
metadata:
  name: bus-realtime-cron-job
  namespace: hyuabot-prod
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: bus-realtime-cron-job
            image: hyuabot-bus-cron-job-image
            imagePullPolicy: Never
            env:
            - name: POSTGRES_ID
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_ID
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_PASSWORD
            - name: POSTGRES_HOST
              value: hyuabot-database
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_EXTERNAL_HOST
              value: "132.226.172.190"
            - name: POSTGRES_EXTERNAL_PORT
              value: "30432"
            - name: POSTGRES_DB
              value: hyuabot
          restartPolicy: OnFailure
