apiVersion: batch/v1
kind: Job
metadata:
  name: shuttle-timetable-job
  namespace: hyuabot-prod
spec:
  template:
    metadata:
      name: shuttle-timetable-job
    spec:
      containers:
      - name: shuttle-timetable-job
        image: hyuabot-shuttle-timetable-job-image
        imagePullPolicy: Never
        env:
          - name: POSTGRES_ID
            valueFrom:
              secretKeyRef:
                name: secret
                key: DB_ID
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: DB_PASSWORD
          - name: POSTGRES_HOST
            value: hyuabot-database
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_DB
            value: hyuabot
      restartPolicy: Never
