apiVersion: v1
kind: Secret
metadata:
  name: API-KEYS
type: Opaque
data:
  BUS_API_KEY: <base64 encoded value>
  METRO_API_KEY: <base64 encoded value>
  DB_ID: <base64 encoded value>
  DB_PASSWORD: <base64 encoded value>
