apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-postgres-pv-volume
  namespace: hyuabot-prod
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/prod/postgres-pv-volume
  storageClassName : prod-postgres-pv-storage
