apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prod-postgresql-pv-claim
  namespace: hyuabot
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: prod-postgres-pv-storage
