apiVersion: v1
kind: Service
metadata:
  name: hyuabot-database
  namespace: hyuabot
  labels:
    app: hyuabot-database
spec:
  type: NodePort
  ports:
  - port: 5432
    nodePort: 30432
  selector:
   app: hyuabot-database