apiVersion: batch/v1
kind: Job
metadata:
  name: migration-database
  namespace: hyuabot
spec:
  template:
    metadata:
      name: migration-database
    spec:
      containers:
      - name: migration-database
        image: postgres:15-alpine
        command: ["sh", "-c", "export PGPASSWORD=$POSTGRES_PASSWORD; psql -h hyuabot-database -U $POSTGRES_ID -d $POSTGRES_DB -f /scripts/create_database.sql"]
        volumeMounts:
        - name: migration-script
          mountPath: /scripts
          readOnly: true
        env:
          - name: POSTGRES_ID
            valueFrom:
              secretKeyRef:
                name: secret
                key: DB_ID
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: DB_PASSWORD
          - name: POSTGRES_DB
            value: hyuabot
      restartPolicy: Never
      volumes:
      - name: migration-script
        configMap:
          name: create-database
