apiVersion: batch/v1
kind: Job
metadata:
  name: building-job
  namespace: hyuabot
spec:
  template:
    metadata:
      name: building-job
    spec:
      containers:
      - name: building-job
        image: localhost:32000/hyuabot/hyuabot-building-updater
        env:
          - name: POSTGRES_ID
            valueFrom:
              secretKeyRef:
                name: secret
                key: DB_ID
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: DB_PASSWORD
          - name: POSTGRES_HOST
            value: hyuabot-database
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_EXTERNAL_HOST
            value: "132.226.172.190"
          - name: POSTGRES_EXTERNAL_PORT
            value: "30432"
          - name: POSTGRES_DB
            value: hyuabot
      restartPolicy: Never