apiVersion: batch/v1
kind: Job
metadata:
  name: initialize-database
spec:
  template:
    metadata:
      name: initialize-database
    spec:
      containers:
      - name: initialize-database
        image: hyuabot-database-initialize
        imagePullPolicy: Never
        env:
          - name: POSTGRES_ID
            valueFrom:
              secretKeyRef:
                name: secret
                key: DB_ID
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: DB_PASSWORD
          - name: POSTGRES_HOST
            value: hyuabot-deployment
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_DB
            value: hyuabot
      restartPolicy: Never
