apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyuabot-redis
  namespace: hyuabot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyuabot-redis
  template:
    metadata:
      labels:
        app: hyuabot-redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
