apiVersion: batch/v1
kind: Job
metadata:
  name: subway-timetable-job
  namespace: hyuabot
spec:
  template:
    metadata:
      name: subway-timetable-job
    spec:
      containers:
      - name: subway-timetable-job
        image: localhost:32000/hyuabot/hyuabot-subway-timetable-updater
        env:
          - name: POSTGRES_ID
            valueFrom:
              secretKeyRef:
                name: secret
                key: DB_ID
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: DB_PASSWORD
          - name: POSTGRES_HOST
            value: hyuabot-database
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_EXTERNAL_HOST
            value: "132.226.172.190"
          - name: POSTGRES_EXTERNAL_PORT
            value: "30432"
          - name: POSTGRES_DB
            value: hyuabot
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: personal-project-vm