apiVersion: batch/v1
kind: CronJob
metadata:
  name: subway-realtime-cron-job
  namespace: hyuabot
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: subway-realtime-cron-job
            image: localhost:32000/hyuabot/hyuabot-subway-realtime-updater
            env:
            - name: POSTGRES_ID
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_ID
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_PASSWORD
            - name: POSTGRES_HOST
              value: hyuabot-database
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: hyuabot
            - name: POSTGRES_EXTERNAL_HOST
              value: "132.226.172.190"
            - name: POSTGRES_EXTERNAL_PORT
              value: "30432"
            - name: METRO_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: METRO_API_KEY
          restartPolicy: OnFailure
