apiVersion: batch/v1
kind: CronJob
metadata:
  name: cafeteria-cron-job
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cafeteria-cron-job
            image: hyuabot-cafeteria-cron-job-image
            imagePullPolicy: Never
            env:
            - name: POSTGRES_ID
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_ID
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_PASSWORD
            - name: POSTGRES_HOST
              value: hyuabot-database
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: hyuabot
          restartPolicy: OnFailure
