apiVersion: v1
kind: Service
metadata:
  name: hyuabot-api
  namespace: hyuabot
  labels:
    app: hyuabot-api
spec:
  type: NodePort
  ports:
  - port: 38000
    nodePort: 30001
  selector:
    app: hyuabot-api