apiVersion: v1
kind: Service
metadata:
  name: hyuabot-api-python-development
  namespace: hyuabot-prod
  labels:
    app: hyuabot-api-python-development
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30004
  selector:
    app: hyuabot-api-python-development