apiVersion: v1
kind: Template
objects:
# Persistent Volume
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: postgres-pv-volume
    namespace: hyuabot
  spec:
    capacity:
      storage: 5Gi
    volumeMode: Filesystem
    accessModes:
    - ReadWriteOnce
    hostPath:
      path: /mnt/data/postgres-pv-volume
    storageClassName : postgres-pv-storage
# Persistent Volume Claim
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: postgres-pv-claim
    namespace: hyuabot
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: postgres-pv-storage
# Deployment for database
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: hyuabot-database
    namespace: hyuabot
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: hyuabot-database
    template:
      metadata:
        labels:
          app: hyuabot-database
      spec:
        volumes:
        - name: postgres-pv-volume
          persistentVolumeClaim:
            claimName: postgres-pv-claim
        containers:
        - name: database
          image: postgres:16-alpine
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: secret
                key: DB_ID
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: DB_PASSWORD
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          - name: POSTGRES_DB
            value: hyuabot
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-pv-volume
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
# Service for database
- apiVersion: v1
  kind: Service
  metadata:
    name: hyuabot-database
    namespace: hyuabot
    labels:
      app: hyuabot-database
  spec:
    type: NodePort
    ports:
    - port: 5432
      nodePort: 35432
    selector:
      app: hyuabot-database
# Create configMap for database from create_database.sql
- apiVersion: kustomize.config.k8s.io/v1beta1
  kind: Kustomization
  configMapGenerator:
  - name: create-database
    files:
    - ../database/create_database.sql
# Migration Job
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: migration-database
    namespace: hyuabot
  spec:
    template:
      metadata:
        name: migration-database
      spec:
        containers:
        - name: migration-database
          image: postgres:16-alpine
          command: ["sh", "-c", "export PGPASSWORD=$POSTGRES_PASSWORD; psql -h hyuabot-database -U $POSTGRES_USER -d $POSTGRES_DB -f /scripts/create_database.sql"]
          volumeMounts:
          - name: migration-script
            mountPath: /scripts
            readOnly: true
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: secret
                key: DB_ID
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: DB_PASSWORD
          - name: POSTGRES_DB
            value: hyuabot
        restartPolicy: Never
        volumes:
        - name: migration-script
          configMap:
            name: create-database
# Initialize Database Job
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: initialize-database
    namespace: hyuabot
  spec:
    template:
      metadata:
        name: initialize-database
      spec:
        containers:
        - name: initialize-database
          image: hyuabot-database-initializer
          env:
          - name: POSTGRES_ID
            valueFrom:
              secretKeyRef:
                name: secret
                key: DB_ID
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: DB_PASSWORD
          - name: POSTGRES_HOST
            value: hyuabot-database
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_DB
            value: hyuabot
        restartPolicy: Never
# Redis Deployment
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: hyuabot-redis
    namespace: hyuabot
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: hyuabot-redis
    template:
      metadata:
        labels:
          app: hyuabot-redis
      spec:
        containers:
        - name: redis
          image: redis:latest-alpine
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 6379
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
