# Bus Realtime Loader
apiVersion: batch/v1
kind: CronJob
metadata:
  name: bus-realtime-cron-job
  namespace: hyuabot
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: bus-realtime-cron-job
            image: localhost:5000/hyuabot-bus-realtime-updater
            env:
            - name: POSTGRES_ID
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_ID
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_PASSWORD
            - name: POSTGRES_HOST
              value: hyuabot-database
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: hyuabot
          restartPolicy: OnFailure
---
# Bus Log Loader
apiVersion: batch/v1
kind: CronJob
metadata:
  name: bus-departure-log-cron-job
  namespace: hyuabot
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: bus-departure-log-cron-job
            image: localhost:5000/hyuabot-bus-log-updater
            env:
            - name: POSTGRES_ID
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_ID
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_PASSWORD
            - name: POSTGRES_HOST
              value: hyuabot-database
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: hyuabot
          restartPolicy: OnFailure
---
# Subway Realtime Loader
apiVersion: batch/v1
kind: CronJob
metadata:
  name: subway-realtime-cron-job
  namespace: hyuabot
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: subway-realtime-cron-job
            image: localhost:5000/hyuabot-subway-realtime-updater
            env:
            - name: POSTGRES_ID
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_ID
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_PASSWORD
            - name: POSTGRES_HOST
              value: hyuabot-database
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: hyuabot
            - name: METRO_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: METRO_API_KEY
          restartPolicy: OnFailure
---
# Reading Room Realtime Loader
apiVersion: batch/v1
kind: CronJob
metadata:
  name: reading-room-cron-job
  namespace: hyuabot
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: reading-room-cron-job
            image: localhost:5000/hyuabot-library-updater
            env:
            - name: POSTGRES_ID
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_ID
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_PASSWORD
            - name: POSTGRES_HOST
              value: hyuabot-database
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: hyuabot
            - name: FIREBASE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: FIREBASE_TOKEN
          restartPolicy: OnFailure
---
# Cafeteria Menu Loader
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cafeteria-cron-job
  namespace: hyuabot
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cafeteria-cron-job
            image: localhost:5000/hyuabot-cafeteria-updater
            env:
            - name: POSTGRES_ID
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_ID
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_PASSWORD
            - name: POSTGRES_HOST
              value: hyuabot-database
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: hyuabot
          restartPolicy: OnFailure